<?php

  $sql_connection = new mysqli("localhost","root","","infinity");
 
 $sql_connection->query("CREATE DATABASE IF NOT EXISTS infinity");

$sql_connection->query("CREATE TABLE IF NOT EXISTS districts(ID INT(10) NOT NULL AUTO_INCREMENT,PRIMARY KEY(ID),NAME VARCHAR(20) NOT NULL UNIQUE)");

$sql_connection->query("CREATE TABLE IF NOT EXISTS members(ID INT(10) NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID),NAME VARCHAR(30) NOT NULL,EMAIL VARCHAR(40) NOT NULL UNIQUE,PHONE_NUMBER VARCHAR(20) NOT NULL,PASSWORD VARCHAR(50) NOT NULL UNIQUE,DISTRICTS_ID INT(10) NOT NULL, FOREIGN KEY(DISTRICTS_ID) REFERENCES districts(ID))");





 

 




 

